apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: jag2-gitops
  description: This is GitOps manifest for jag2   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: jag2
    janus-idp.io/tekton: jag2 
    backstage.io/kubernetes-id: jag2 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:jag2
