apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jag2
  janus-idp.io/tekton: jag2
  backstage.io/kubernetes-id: jag2
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jag2
resources: 
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml 
