apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: jag2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jag2 
  name: jag2
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: jag2
    weight: 100 
