apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jag2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jag2 
  name: jag2
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jag2 
